// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PEC.Models
{
    public partial class Clinica : DbContext
    {
        public Clinica()
        {
        }

        public Clinica(DbContextOptions<Clinica> options)
            : base(options)
        {
        }

        public virtual DbSet<VwEspecialidadeConvenioChat> VwEspecialidadeConvenioChat { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VwEspecialidadeConvenioChat>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vw_Especialidade_ConvenioChat");

                entity.Property(e => e.Especialidade).IsUnicode(false);

                entity.Property(e => e.NmConvenio).IsUnicode(false);

                entity.Property(e => e.NmEspecialidade).IsUnicode(false);
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}