// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PEC.Models
{
    public partial class teste : DbContext
    {
        public teste()
        {
        }

        public teste(DbContextOptions<teste> options)
            : base(options)
        {
        }

        public virtual DbSet<VwPecMenuUsuarios> VwPecMenuUsuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VwPecMenuUsuarios>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vw_PEC_Menu_Usuarios", "SIA");

                entity.Property(e => e.NmDescricao).IsUnicode(false);

                entity.Property(e => e.NmUrl).IsUnicode(false);
            });

            modelBuilder.HasSequence<int>("Movimentacao_ContabilCounter", "SIA").StartsAt(0);

            modelBuilder.HasSequence("MovMateDsDoctoSeq", "SIA").StartsAt(200001);

            modelBuilder.HasSequence("Segreg_NR_DC_REC", "SIA");

            modelBuilder.HasSequence("SegregNrDcRecSeq", "SIA");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}