// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PEC.Models
{
    public partial class usp_Separar_Consulta_AgendaChatResult
    {
        public long? Ordem { get; set; }
        public int? ID_Consulta { get; set; }
        public DateTime? DT_Consulta { get; set; }
        public string Nome { get; set; }
        public string Data { get; set; }
        public string Situacao { get; set; }
        public string Especialidade { get; set; }
        public string NM_Paciente { get; set; }
        public string Telefone { get; set; }
        public string TipoConsulta { get; set; }
        public string Motivo { get; set; }
        public string Sexo { get; set; }
        public DateTime? DT_Nascto { get; set; }
        public string eMail { get; set; }
        public string CPF { get; set; }
        public int? ID_Medico { get; set; }
        public int? ID_Especialidade { get; set; }
        public int? ID_MedicoEspec { get; set; }
        public DateTime? HS_Inicial { get; set; }
        public string HS_Consulta { get; set; }
        public int? QT_Marcadas { get; set; }
        public int? FL_Prioridade { get; set; }
        public int? ID_Convenio { get; set; }
    }
}
