// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PEC.Models
{
    public partial class VwPecMenuUsuarios
    {
        [Column("ID_Usuario")]
        public int IdUsuario { get; set; }
        [Column("ID_Sistema")]
        public int IdSistema { get; set; }
        [Required]
        [Column("NM_Descricao")]
        [StringLength(60)]
        public string NmDescricao { get; set; }
        [Required]
        [Column("NM_Url")]
        [StringLength(60)]

        public string NM_Url { get; set; }

        [Column("NR_Menu_Pai")]
        public int NrMenuPai { get; set; }


    }
}