// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PEC.Models
{
    public partial class ADSCentralContext : DbContext
    {
        public ADSCentralContext()
        {
        }

        public ADSCentralContext(DbContextOptions<ADSCentralContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Especialidade> Especialidade { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Especialidade>(entity =>
            {
                entity.HasKey(e => e.IdEspecialidade)
                    .HasName("PK_Especialidade_1");

                entity.HasIndex(e => e.NmEspecialidade)
                    .HasName("IX_Especialidade");

                entity.Property(e => e.IdEspecialidade).HasColumnName("ID_Especialidade");

                entity.Property(e => e.Cbo)
                    .HasColumnName("CBO")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CdAmb)
                    .HasColumnName("CD_Amb")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CodigoReceita)
                    .HasColumnName("Codigo_Receita")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.FlAtiva).HasColumnName("FL_Ativa");

                entity.Property(e => e.FlCobrarConsulta).HasColumnName("FL_Cobrar_Consulta");

                entity.Property(e => e.FlFeminino).HasColumnName("FL_Feminino");

                entity.Property(e => e.FlGeral).HasColumnName("FL_Geral");

                entity.Property(e => e.FlMasculino).HasColumnName("FL_Masculino");

                entity.Property(e => e.FlSecao).HasColumnName("FL_Secao");

                entity.Property(e => e.IdExameSessao).HasColumnName("ID_Exame_Sessao");

                entity.Property(e => e.NmEspecialidade)
                    .IsRequired()
                    .HasColumnName("NM_Especialidade")
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}