// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PEC.Context
{
    public partial class VwEspecialidadeConvenioChat
    {
        [Column("ID_Convenio")]
        public int IdConvenio { get; set; }
        [Required]
        [Column("NM_Convenio")]
        [StringLength(100)]
        public string NmConvenio { get; set; }
        public long? Codigo { get; set; }
        [StringLength(60)]
        public string Especialidade { get; set; }
        [Column("ID_Especialidade")]
        public int IdEspecialidade { get; set; }
        [Required]
        [Column("NM_Especialidade")]
        [StringLength(60)]
        public string NmEspecialidade { get; set; }
    }
}